title: jarrod m. burges
description:
baseurl: ""
url: https://jarrodburges.com

theme: cvless

# site settings
taglong:
tagshort:
cv: true

# author settings
author:
  name: Jarrod M. Burges
  email:
photo: assets/img/profile.jpeg
address:
phone:

# profile links
profile:
  linkedin: https://www.linkedin.com/in/jarrod-burges
  orcid: https://orcid.org/0009-0007-9044-1174
  github: https://github.com/jarrod-burges

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
